- month: January
  first_training_date: 9th
  first_training: Monthly Safety Drills - SCBA/PPE Module - Call Discussions - Drivers Training Re-Fresher
  second_training_date: 23rd
  second_training: FF Skills/Ropes & Knots - FF Skills/Tool & Equip - Call Discussions - Drivers Training Re-Fresher

- month: February
  first_training_date: 6th
  first_training: Monthly Safety Drills	- FF Skills / Salvage - Call Discussions - Drivers Training Re-Fresher
  second_training_date: 20th
  second_training: FF Skills/FF Rescue - EMT SGA-DEIB - Call Discussions - Drivers Training Re-Fresher

- month: March
  first_training_date: 5th
  first_training: Monthly Safety Drills - Hose Evolutions - Call Discussions - Drivers Training Re-Fresher
  second_training_date: 19th
  second_training: FF Skills/Force Entry - EMT-OTEP1 BL 7:00 - Call Discussions - Drivers Training Re-Fresher

- month: April
  first_training_date: 9th
  first_training: Monthly Safety Drills - SCBA/PPE Module - Incident Simulations - Call Discussions
  second_training_date: 23rd
  second_training: Monthly Safety Drills - Cleanup of Open House, Call Discussions - Drivers Training Re-Fresher

- month: May
  first_training_date: 7th
  first_training: Marine 7 Training - Cleanup for Open House - Call Discussions - Drivers Training Re-Fresher
  second_training_date: 21st or 26th
  second_training: Open House - FF Skills/Tools & Equip -  EMT-OTEP1 BL 7:00 - Call Discussions 

- month: June
  first_training_date: 4th
  first_training: Monthly Safety Drills - Drivers Training Re-Fresher - Call Discussions - Incident Simulations
  second_training_date: 18th
  second_training: Hose Evolutions - Skills/Port. Masters Streams, Call Discussions - IMS/ Accountability Review

- month: July
  first_training_date: 9th
  first_training: Monthly Safety Drills - SCBA/PPE Module - IMS/Accountability Review, Call Discussions
  second_training_date: 23rd
  second_training: FF Skills/Pros. Press Vent - FF Skills/Vertical Ventilation - IMS / Accountability Review - Call Discussions

- month: August
  first_training_date: 6th or 10th
  first_training: Monthly Safety Drills - Fun Run - Ground Ladders - Call Discussions
  second_training_date: 20th
  second_training: FF Skills/Vehicle Extrications - Hose Evolutions - Call Discussions - Drivers Training Re-Fresher

- month: September
  first_training_date: 3rd
  first_training: FF Skills/Fire Extinguishers - Call Discussions - Drivers Training Re-Fresher
  second_training_date: 17th
  second_training: Multi-Company Operations - FF Skills/FF Rescue - EMT-OTEP3 BL 7:00 - Call Discussions

- month: October
  first_training_date: 8th
  first_training: Hose Evolutions - FF Skills/Tools & Equip - Incident Simulations - Call Discussions
  second_training_date: 22nd
  second_training: Monthly Safety Drills - SCBA/PPE Module - FF Skills/Force Entry - Call Discussions

- month: November
  first_training_date: 5th
  first_training: Drivers Training Re-Fresher - Call Discussions - EMT-SGA-DEFIB
  second_training_date: 19th
  second_training: FF Skills/Ground Ladders - FF Skills/Hoisting - Call Discussions - EMT-OTEP3 BL 7:00

- month: December
  first_training_date: 3rd
  first_training: Monthly Safety Drills - Multi Company Operations - Call Discussions
  second_training_date: 17th
  second_training: FF Skills/Vertical Ventilation - FF Skills/Salvage - Call Discussions